const pokemons = [
    {
        name: 'Pikachu',
        type: 'Electric',
        strength: '46',
        level: '2',
        attacks: ['Thunderbolt', 'Quick Attack', 'Irontail', 'Tackle', 'Thunderwave'],  
        imagepath: "Pikachu.png",
    },
    {
        name: 'Charmander',
        type: 'Fire',
        strength: '40',
        level: '1',
        attacks: ['Ember', 'Flamethrower', 'Firespin', 'Tackle'],  
        imagepath: "Charmander.png",
    },
    {
        name: 'Squirtle',
        type: 'Water',
        strength: '40',
        level: '1',
        attacks: ['Water Gun', 'Bubble Attack', 'Body Slam', 'Tackle', 'Water splash'],  
        imagepath: "Squirtle.png",
    },
    {
        name: 'Bulbasaur',
        type: 'Grass',
        strength: '40',
        level: '1',
        attacks: ['Razor Leaf', 'Poison powder', 'Vine Wipe', 'Tackle', 'Solar Beam'],
        imagepath: "Bulbasaur.png",
    },
    {
        name: 'Caterpie',
        type: 'Grass',
        strength: '30',
        level: '1',
        attacks: ['String Shot', 'Bug Bite', 'Tackle', 'Surprice Attack'],  
        imagepath: "Caterpie.png",
    },
    {
        name: 'Pidgey',
        type: 'Air',
        strength: '40',
        level: '1',
        attacks: ['Gust', 'Wing Attack', 'Peak'],  
        imagepath: "Pidgey.png",
    },
    {
        name: 'Vulpix',
        type: 'Fire',
        strength: '40',
        level: '1',
        attacks: ['Live Coal', 'Flare', 'Tail wipe', 'Tackle', 'Smash Kick'],  
        imagepath: "Vulpix.png",
    },
    {
        name: 'Meowth',
        type: 'Normal',
        strength: '40',
        level: '2',
        attacks: ['Scratch', 'Quick Attack', 'Tail wipe', 'Tackle'],  
        imagepath: "Meowth.png",
    },
    {
        name: 'Psyduck',
        type: 'Psykick',
        strength: '40',
        level: '1',
        attacks: ['Headache', 'Scratch', 'Psykick'],  
        imagepath: "Psyduck.png",
    },
    {
        name: 'Gastly',
        type: 'Ghost',
        strength: '40',
        level: '1',
        attacks: ['Sleep pulse', 'Fade out', 'Smog', 'Omnious Eyes'],  
        imagepath: "Gastly.png",
    },
    {
        name: 'Onix',
        type: 'Ground',
        strength: '50',
        level: '1',
        attacks: ['Rock Throw', 'Dig Deep', 'Tail smash', 'Tackle'],  
        imagepath: "Onix.png",
    },
    {
        name: 'Cubone',
        type: 'Ground',
        strength: '40',
        level: '1',
        attacks: ['Head Butt', 'Boomerang', 'Bone Attack', 'Tackle', 'Thunderwave'],
        imagepath: "Cubone.png" 
    },
];

export default pokemons;
